source 'https://github.com/tpctt/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "8.0"

target:SuggestInputViewDemo  do
pod 'ZLPhotoBrowser'


end



target:SuggestInputView do
    pod 'ZLPhotoBrowser','~>2.5.5'
    
    
end

